application: par
 
default_versions:
  # Specify the version of platform-helper your configuration is designed to work with
  # Get the version by running `platform-helper --version`
  platform-helper: 13.2.0
 
deploy_repository: OfficeForProductSafetyAndStandards/opss-par-v4-deploy
 
environments:
  "*":
    accounts:
      deploy:
        name: "primary-authority-register"
        id: "970547347857"
      dns:
        name: "dev"
        id: "011755346992"
    vpc: primary-authority-register
  dev:
  test:
  staging:
  prod:
    accounts:
      # The AWS account your application will be deployed to
      deploy:
        name: "primary-authority-register-prod"
        id: "597088022393"
      # The AWS account where your application's DNS lives
      dns:
        name: "live"
        id: "684092750218"
    # The name of the VPC your environment should be deployed into
    vpc: primary-authority-register-prod
 
environment_pipelines:
  main:
    account: primary-authority-register
    branch: main
    slack_channel: "/codebuild/slack_oauth_channel"
    trigger_on_push: true
    pipeline_to_trigger: prod-main
    environments:
      dev:      
  prod-main:
    account: primary-authority-register-prod
    branch: main
    slack_channel: "/codebuild/slack_oauth_channel"
    trigger_on_push: false
    environments:
      prod:
        requires_approval: true
 
codebase_pipelines:
  par:
    repository: OfficeForProductSafetyAndStandards/opss-par-v4
    slack_channel: /codebuild/slack_oauth_channel
    services:
      - run_group_1:
          - web
    pipelines:
      - name: main
        branch: main
        environments:
          - name: dev         
      - name: tagged
        tag: true
        environments:
          - name: prod
 
extensions:
  # Add an application load balancer for each environment to route traffic to the application
  alb:
    type: alb
    # This allows you to configure the application load balancer for each environment
    environments:
      dev:
        cdn_domains_list:
          dev.primary-authority-register.uktrade.digital: ["internal", "primary-authority-register.uktrade.digital", "enable_record"]          
      prod:
        cdn_domains_list:
          primary-authority-register.prod.uktrade.digital: ["internal", "primary-authority-register.prod.uktrade.digital", "enable_record"]
 
  bucket:
    type: s3
    services:
      - web
    environments:
      dev:
        bucket_name: par-dev-s3
      prod:
        bucket_name: par-prod-s3
 